# Generated by Django 4.2.7 on 2024-12-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_acc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
